# Generated by Django 6.0.3 on 2026-09-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_teacher_remove_student_group_student_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='date',
            field=models.DateField(blank=True, help_text='Необязательно: задайте дату, если занятие привязано к конкретному дню', null=True, verbose_name='Конкретная дата'),
        ),
    ]
