# Generated by Solar Mini4 for wagtailpag

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


def copy_subject_values(apps, schema_editor):
    Lesson = apps.get_model("home", "Lesson")
    Subject = apps.get_model("blog", "Subject")
    for lesson in Lesson.objects.all():
        subject_name = (lesson.subject or "").strip()
        if not subject_name:
            continue
        subject, created = Subject.objects.get_or_create(
            name=subject_name,
            defaults={"slug": subject_name},
        )
        if not created:
            subject = Subject.objects.get(name=subject_name)
            if subject.slug != subject_name:
                subject.slug = subject_name
                subject.save(update_fields=["slug"])
        lesson.subject_new = subject
        lesson.save(update_fields=["subject_new"])


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_blogpostpage_bloglistingpage_intro"),
        ("home", "0006_aboutpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedulepage",
            name="lessons",
            field=wagtail.fields.StreamField(
                [("lesson", 7)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Предмет", "max_length": 150}),
                    1: ("wagtail.blocks.ChoiceBlock", [], {"choices": [("mon", "Понедельник"), ("tue", "Вторник"), ("wed", "Среда"), ("thu", "Четверг"), ("fri", "Пятница"), ("sat", "Суббота"), ("sun", "Воскресенье")], "label": "День недели"}),
                    2: ("wagtail.blocks.DateBlock", (), {"label": "Дата", "required": False}),
                    3: ("wagtail.blocks.TimeBlock", (), {"label": "Начало"}),
                    4: ("wagtail.blocks.TimeBlock", (), {"label": "Конец"}),
                    5: ("wagtail.blocks.CharBlock", (), {"label": "Аудитория", "max_length": 50, "required": False}),
                    6: ("wagtail.blocks.CharBlock", (), {"label": "Группы (через запятую)", "max_length": 200, "required": False}),
                    7: ("wagtail.blocks.StructBlock", [[("subject", 0), ("weekday", 1), ("date", 2), ("start_time", 3), ("end_time", 4), ("room", 5), ("groups", 6)]], {}),
                },
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="subject_new",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lessons",
                to="blog.subject",
                verbose_name="Предмет",
            ),
        ),
        migrations.RunPython(copy_subject_values, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="lesson",
            name="subject",
        ),
        migrations.RenameField(
            model_name="lesson",
            old_name="subject_new",
            new_name="subject",
        ),
    ]
