# Generated by Django 6.0.3 on 2026-09-15 16:48

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ODTDocumentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('odt_document', wagtail.fields.StreamField([('document', 0)], block_lookup={0: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': True})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='bloglistingpage',
            name='odt_document',
            field=wagtail.fields.StreamField([('document', 0)], blank=True, block_lookup={0: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': True})}, null=True),
        ),
    ]
