# Generated by Django 5.1.6 on 2026-09-29 17:49

import blog.models
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_activity_subject_delete_student_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата публикации')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Вступление')),
                ('body', wagtail.fields.RichTextField(blank=True, verbose_name='Текст статьи')),
                ('attached_documents', wagtail.fields.StreamField([('document', 0)], blank=True, block_lookup={0: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': True})}, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(blog.models.ODTDocumentSearchMixin, 'wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='bloglistingpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Вступление'),
        ),
    ]
