# Generated by Django 5.1.6 on 2026-10-08 14:52

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogpostpage_bloglistingpage_intro'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamFieldDemoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('content', wagtail.fields.StreamField([('richtext', 0), ('list_items', 2), ('info', 7), ('document', 8)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('blog.models.ListItemBlock', (), {}), 2: ('wagtail.blocks.ListBlock', (1,), {}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Заголовок блока', 'required': True}), 4: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Текст блока', 'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 6: ('wagtail.blocks.ListBlock', (5,), {'help_text': 'Теги блока', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('heading', 3), ('text', 4), ('tags', 6)]], {}), 8: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': False})}, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
